const receipe = [
  {
    id: 1,
    name: "Es Cendol",
    region: "Jawa Tengah, Jawa Timur, dan sekitarnya",
    image: "https://www.sasa.co.id/medias/page_medias/es_cendol_nangka.jpg",
    ingredients: [
      "100 gram tepung beras",
      "50 gram tepung hunkwe (tepung beras ketan)",
      "750 ml air",
      "200 ml santan kental",
      "100 gram gula merah, sisir halus",
      "Sejumput garam",
      "Es batu secukupnya",
    ],
    instructions: [
      "Campur tepung beras dan tepung hunkwe, tambahkan air sedikit demi sedikit sambil diaduk hingga rata.",
      "Saring adonan dengan saringan halus ke dalam panci.",
      "Rebus adonan sambil terus diaduk hingga meletup-letup dan kental. Angkat dan biarkan dingin.",
      "Didihkan air, tambahkan santan, gula merah, dan garam.",
      "Aduk hingga gula larut, angkat dan biarkan dingin.",
      "Siapkan gelas saji, masukkan cendol yang sudah dingin, tambahkan es batu, lalu tuang larutan santan gula merah di atasnya. Sajikan segera.",
    ],
  },
  {
    id: 2,
    name: "Bajigur",
    region: "Jawa Barat",
    image:
      "https://asset.kompas.com/crops/NwjTDQ2A5YgdlFNkE7HQ1VF5PNs=/111x83:735x499/750x500/data/photo/2020/03/28/5e7eb826a19c9.jpg",
    ingredients: [
      "200 ml air",
      "100 ml santan kental",
      "1 sdm gula merah, sisir halus",
      "1 sdm bubuk kopi",
      "1 sdm bubuk jahe",
      "Sejumput garam",
      "Secubit kayu manis bubuk (opsional)",
    ],
    instructions: [
      "1. Rebus air, tambahkan gula merah, bubuk kopi, bubuk jahe, garam, dan kayu manis bubuk. Aduk rata.",
      "2. Setelah mendidih dan gula merah larut, tambahkan santan kental. Aduk hingga rata dan panas kembali.",
      "3. Saring bajigur ke dalam gelas saji.",
      "4. Bajigur siap disajikan selagi hangat.",
    ],
  },
  {
    id: 3,
    name: "Wedang Ronde",
    region: "Jawa Tengah",
    image:
      "https://asset.kompas.com/crops/RJ97KL0xzjUKnFnBBOHwNIp60D8=/19x0:1000x654/750x500/data/photo/2021/12/31/61cea13d20626.jpg",
    ingredients: [
      "1 liter air",
      "200 gram ketan, rendam semalam, tiriskan",
      "100 gram kacang tanah, sangrai, kupas kulitnya",
      "100 gram gula merah, sisir halus",
      "1 lembar daun pandan, simpulkan",
      "Sejumput garam",
    ],
    instructions: [
      "1. Rebus air hingga mendidih.",
      "2. Masukkan ketan yang sudah direndam dan daun pandan ke dalam air mendidih. Masak hingga ketan menjadi empuk.",
      "3. Sambil menunggu ketan matang, campurkan gula merah dan garam ke dalam air ketan. Aduk hingga gula merah larut sempurna.",
      "4. Angkat ketan dan tiriskan.",
      "5. Ambil sepotong ketan yang sudah matang, bulatkan menjadi bulatan kecil (ronde).",
      "6. Celupkan ronde ke dalam kacang tanah sangrai yang sudah dihaluskan.",
      "7. Wedang Ronde siap disajikan hangat. Selamat menikmati!",
    ],
  },
  {
    id: 4,
    name: "Wedang Jahe",
    region: "Jawa Tengah",
    image:
      "https://www.masakapahariini.com/wp-content/uploads/2018/12/shutterstock_338815997.jpg",
    ingredients: [
      "500 ml air",
      "50 gram jahe, memarkan",
      "2 lembar daun pandan, simpulkan",
      "2 batang serai, memarkan",
      "3 sdm gula merah, sisir halus",
      "1 sdm madu (opsional)",
      "Secubit garam",
    ],
    instructions: [
      "1. Rebus air hingga mendidih.",
      "2. Masukkan jahe yang sudah dimemarkan dan daun pandan ke dalam air mendidih. Masak hingga jahe mengeluarkan aroma harum.",
      "3. Sambil menunggu jahe matang, campurkan gula merah dan garam ke dalam air jahe. Aduk hingga gula merah larut sempurna.",
      "4. Angkat jahe dan daun pandan, saring air jahe ke dalam gelas saji.",
      "5. Wedang Jahe siap disajikan hangat. Selamat menikmati!",
    ],
  },
  {
    id: 5,
    name: "Bandrek",
    region: "Sunda, Jawa Barat",
    image:
      "https://cdns.klimg.com/mav-prod-resized/480x/ori/feedImage/2023/03/08/194728.086-bandrek-dulu-dijual-mahal-kini-1.jpeg",
    ingredients: [
      "500 ml air",
      "100 gram gula merah, sisir halus",
      "2 lembar daun pandan, simpulkan",
      "2 batang serai, memarkan",
      "2 cm jahe, memarkan",
      "2 sdm bubuk ketumbar",
      "2 sdm bubuk jahe",
      "1 sdt garam",
      "1 sdt merica",
      "1 sdt cengkeh",
      "1 sdt kayu manis bubuk",
      "100 ml santan kental",
    ],
    instructions: [
      "1. Rebus air hingga mendidih.",
      "2. Masukkan gula merah, daun pandan, serai, jahe, bubuk ketumbar, bubuk jahe, garam, merica, cengkeh, dan kayu manis bubuk ke dalam air mendidih. Aduk rata.",
      "3. Masak hingga bumbu mengeluarkan aroma harum.",
      "4. Tambahkan santan kental, aduk rata dan panas kembali.",
      "5. Angkat dan saring bandrek ke dalam gelas saji.",
      "6. Bandrek siap disajikan hangat. Selamat menikmati!",
    ],
  },
  {
    id: 6,
    name: "Es Doger",
    region: "Betawi, Jakarta",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.kompas.com%2Ffood%2Fread%2F2023%2F03%2F26%2F193656675%2Fresep-es-doger-takjil-segar-inspirasi-signature-dish-ami-masterchef&psig=AOvVaw3u2kcL0FKjBAnJ3iDCcLP5&ust=1715607899490000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCIjyos2fiIYDFQAAAAAdAAAAABAE",
    ingredients: [
      "200 ml santan kental",
      "100 gram kelapa muda, parut",
      "100 gram gula merah, sisir halus",
      "100 gram kacang tanah, sangrai, haluskan",
      "100 gram alpukat, potong kotak",
      "100 gram tape singkong, potong kotak",
      "100 gram nangka, potong kotak",
      "100 gram ketan hitam, kukus, sisir",
      "100 gram kolang-kaling",
      "100 gram es serut",
    ],
    instructions: [
      "1. Campur santan kental dan gula merah, aduk rata.",
      "2. Siapkan gelas saji, masukkan kelapa muda, kacang tanah, alpukat, tape singkong, nangka, ketan hitam, kolang-kaling, dan es serut.",
      "3. Tuang santan gula merah ke dalam gelas saji.",
      "4. Es Doger siap disajikan. Selamat menikmati!",
    ],
  },
  {
    id: 7,
    name: "Sinom",
    region: "Jawa Tengah, Jawa Timur",
    image:
      "https://cdns.klimg.com/merdeka.com/i/w/news/2021/07/14/1329685/540x270/5-resep-jamu-sinom-yang-enak-dan-sehat-mudah-dibuat.jpg",
    ingredients: [
        "1 liter air",
        "100 gram gula merah, sisir halus",
        "2 lembar daun jeruk, simpulkan",
        "1 batang serai, memarkan",
        "1 sdt asam jawa, larutkan dengan sedikit air",
        "Secubit garam",
        ],
    instructions: [
        "1. Rebus air hingga mendidih.",
        "2. Masukkan gula merah, daun jeruk, serai, dan garam ke dalam air mendidih. Aduk rata.",
        "3. Masak hingga gula merah larut sempurna.",
        "4. Tambahkan larutan asam jawa, aduk rata.",
        "5. Angkat dan saring sinom ke dalam gelas saji.",
        "6. Sinom siap disajikan hangat. Selamat menikmati!",
    ],
  },
  {
    id: 8,
    name: "Sekoteng",
    region: "Jawa Tengah, Jawa Timur",
    image:
      "https://asset.kompas.com/crops/pG7h1T-dUC-Fea9UoMiuzoELJZ0=/40x57:912x638/750x500/data/photo/2022/09/15/632324786c2c7.jpg",
    ingredients: [
        "1 liter air",
        "100 gram gula merah, sisir halus",
        "100 gram kacang tanah, sangrai, haluskan",
        "100 gram kolang-kaling",
        "100 gram mutiara, rebus hingga matang",
        "100 gram tape singkong, potong kotak",
        "100 gram ketan hitam, kukus, sisir",
        "100 gram jahe, memarkan",
        "Secubit garam",
        ],
    instructions: [
        "1. Rebus air hingga mendidih.",
        "2. Masukkan gula merah, kacang tanah, kolang-kaling, mutiara, tape singkong, ketan hitam, jahe, dan garam ke dalam air mendidih. Aduk rata.",
        "3. Masak hingga bahan-bahan matang dan bumbu meresap.",
        "4. Sekoteng siap disajikan hangat. Selamat menikmati!",
    ],
  },
  {
    id: 9,
    name: "Sorbet Buah Naga",
    region: "Bali",
    image:
      "https://www.kompas.com/food/read/2022/05/09/200000775/resep-sorbet-buah-naga-segar-dan-mudah-dibuat",
    ingredients: [
        "500 gram buah naga, kupas, potong kotak",
        "100 gram gula pasir",
        "100 ml air",
        "1 sdm air jeruk nipis",
        ],
    instructions: [
        "1. Blender buah naga hingga halus, saring.",
        "2. Masak gula pasir dengan air hingga larut, dinginkan.",
        "3. Campurkan air gula dan air jeruk nipis ke dalam jus buah naga, aduk rata.",
        "4. Tuang ke dalam cetakan, simpan dalam freezer hingga beku.",
        "5. Sorbet Buah Naga siap disajikan. Selamat menikmati!",
    ],
  },
  {
    id: 10,
    name: "Wedang Uwuh",
    region: "Yogyakarta",
    image:
      "https://assets.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/2023/08/05/wedang-uwuh-4201164030.jpg ",
    ingredients: [
        "1 liter air",
        "100 gram gula merah, sisir halus",
        "2 lembar daun pandan, simpulkan",
        "2 batang serai, memarkan",
        "2 cm jahe, memarkan",
        "1 sdt cengkeh",
        "1 sdt kayu manis bubuk",
        "1 sdt merica",
        "1 sdt garam",
        ],
    instructions: [
        "1. Rebus air hingga mendidih.",
        "2. Masukkan gula merah, daun pandan, serai, jahe, cengkeh, kayu manis bubuk, merica, dan garam ke dalam air mendidih. Aduk rata.",
        "3. Masak hingga bumbu mengeluarkan aroma harum.",
        "4. Wedang Uwuh siap disajikan",
        "5. Selamat menikmati!",
    ],
  }
];

module.exports = receipe;
